"""
curriculum.py — the free multi unit curriculum, and the badges that go with it.

Every unit here is a paraphrase of one stretch of

    Anderson, Daniel J., et al. Student Guide to Artificial Intelligence,
    AI-U 2025, Elon Edition. Elon University and American Association of
    Colleges and Universities, 2025.

The guide is published under a Creative Commons Attribution NonCommercial
ShareAlike licence, so paraphrasing it inside a free course is exactly what it
is for. The wording below is ours. The ideas, the checklists and the framework
for a prompt are the guide's, and the source line on each unit says which pages
it came from.

House rule for every learner facing string in this file, and in every template
that reads it: no dashes, no colons, no semicolons.
"""

from __future__ import annotations

SOURCE_SHORT = "Anderson et al., Student Guide to Artificial Intelligence, AI U 2025, Elon Edition"

# ─────────────────────────────────────────────────────────────────────────────
# UNITS
# ─────────────────────────────────────────────────────────────────────────────

UNITS = [
    {
        "id": "unit1",
        "number": 1,
        "slug": "where_ai_already_lives",
        "title": "WHERE AI ALREADY LIVES",
        "blurb": "Before you can use a tool well you have to know what it is and where it already sits in your day.",
        "color": "#7fc4e8", "tint": "#f2fafe", "dark": "#4a7891",
        "source": "Paraphrased from pages 6 and 7 of the guide",
        "minutes": 8,
        "cards": [
            {
                "heading": "WHAT GENERATIVE AI ACTUALLY IS",
                "body": "Generative AI tools run machine learning over your prompt, plus whatever data or images you hand them, and produce something new. That output can be writing, a voice, a picture, a video or a piece of code. The output imitates the human acts of learning, reasoning, solving a problem and choosing.",
                "bullets": [
                    "Imitating those acts is not the same as performing them.",
                    "The model has no experience of the world it is describing.",
                    "Treat everything it produces as a draft written by a very fast stranger.",
                ],
            },
            {
                "heading": "NEVER FORGET THAT IT IS NOT A PERSON",
                "body": "A model can hold a warm and convincing personality in place for hours. It still has no feelings, no stake in your life and no memory of caring. The guide is blunt about this because the illusion is strong. Use these tools to widen what you can do. Do not use them to replace who you talk to.",
                "bullets": [
                    "Augment your human capability rather than hand it over.",
                    "A chatbot that agrees with everything you say is not a friend. It is a mirror.",
                ],
            },
            {
                "heading": "IT IS ALREADY IN YOUR POCKET",
                "body": "You have been using AI for years without calling it that. Search results, the row of shows a streaming service pushes at you, a maps route, a music queue, a voice assistant, a social feed and a ride match are all ranked or generated by models.",
                "bullets": [
                    "Word processors, slide tools and spreadsheets now ship with an assistant built in.",
                    "Meeting software will transcribe you, summarise you and write your follow ups.",
                    "Agents are the newer shape. They take in a goal, plan, and carry out a run of tasks on your behalf.",
                ],
            },
            {
                "heading": "SIX FAMILIES OF TOOL",
                "body": "The guide sorts the landscape into families. Knowing the family tells you what the tool is likely to be good at, which matters more than knowing this month's product names.",
                "bullets": [
                    "General chat assistants that write, explain and reason across most subjects.",
                    "Specialist tools for research, writing and code that are tuned for one job.",
                    "Creative generators for images, video, sound and design.",
                    "Analytical tools for statistics, mathematics, business intelligence and charts.",
                    "Embedded assistants living inside software you already pay for.",
                    "Open and customisable models from community hubs, plus aggregators that put many models behind one window.",
                ],
            },
            {
                "heading": "FREE OR PAID",
                "body": "Your school may already hold licences that give you a full account at no cost, so check before you spend anything. Free versions of most major platforms are good enough to learn on. Only pay once you can say exactly which limit you keep hitting.",
                "bullets": [
                    "Test the same task in several tools before you subscribe to any of them.",
                    "A more expensive model is not automatically a more correct one.",
                ],
            },
        ],
        "so": "Naming the family and the limits of a tool is the first real AI skill. Everything later in this course is built on it.",
        "exercises": ["tool_match"],
    },

    {
        "id": "unit2",
        "number": 2,
        "slug": "what_ai_means_for_your_education",
        "title": "WHAT IT MEANS FOR YOUR EDUCATION",
        "blurb": "The question is not whether AI touches your degree. It is whether it grows your thinking or quietly does it for you.",
        "color": "#a98fd4", "tint": "#f6f1ff", "dark": "#7d6ea8",
        "source": "Paraphrased from pages 7 and 24 of the guide",
        "minutes": 9,
        "cards": [
            {
                "heading": "THE GROUND IS MOVING UNDER YOUR DEGREE",
                "body": "Teaching models are changing while you are enrolled in them. Most employers will expect you to arrive already able to work with these tools. And the tools themselves will keep turning over, so the durable skill is learning how to learn.",
                "bullets": [
                    "Assignments are being redesigned around what a model cannot do for you.",
                    "Academic leaders surveyed for the guide expect large effects on the teaching model and on learning outcomes inside five years.",
                    "They named the upside as customised learning, stronger research skills, clearer writing and more creativity.",
                    "They named the downside as integrity worries, shorter attention, overreliance and a widening digital gap.",
                ],
            },
            {
                "heading": "FIVE THINGS WORTH LEARNING TO DO",
                "body": "The guide lists what a student should actually be able to do with AI. Notice that every item is a way of getting further into the material, not a way of getting around it.",
                "bullets": [
                    "Research, organise and summarise information.",
                    "Sharpen your writing and the way you communicate.",
                    "Work through complicated data, find the pattern and solve the problem.",
                    "Make things and push an original idea further than you could alone.",
                    "Study better, with material shaped to what you do not yet know.",
                ],
            },
            {
                "heading": "AUGMENT OR REPLACE",
                "body": "The whole guide turns on one distinction. A use that augments you leaves you more capable when the tool is taken away. A use that replaces you leaves you less capable. The same tool and even the same prompt can land on either side depending on what you do next.",
                "bullets": [
                    "Asking for three counterarguments to your thesis, then arguing back, augments you.",
                    "Asking for the finished essay replaces you.",
                    "Asking a model to quiz you on a chapter augments you.",
                    "Asking it for the answer key before you try replaces you.",
                ],
            },
            {
                "heading": "GUARD AGAINST OVERRELIANCE",
                "body": "Overreliance is the failure mode the guide keeps circling back to. It is quiet, it feels efficient and it is only visible later, in an exam room or a job interview, when the tool is not there.",
                "bullets": [
                    "Exercise the mental muscle you are tempted to outsource.",
                    "Notice when you reach for a model out of habit rather than need.",
                ],
            },
        ],
        "so": "Every AI decision you make in a course is really a decision about which version of yourself graduates.",
        "exercises": ["lean_check"],
    },

    {
        "id": "unit3",
        "number": 3,
        "slug": "the_anatomy_of_a_prompt",
        "title": "THE ANATOMY OF A PROMPT",
        "blurb": "A weak prompt is not a short prompt. It is a prompt missing one of its parts.",
        "color": "#e79ec0", "tint": "#fdeef4", "dark": "#96637c",
        "source": "Paraphrased from page 8 of the guide",
        "minutes": 12,
        "cards": [
            {
                "heading": "THE SIX PARTS",
                "body": "The guide lays out the key elements of an effective prompt. Four of them are needed almost every time. Two are optional and are worth adding whenever the answer has a shape or a voice you care about.",
                "bullets": [
                    "Your goal. What you are ultimately trying to accomplish, stated as an outcome rather than a request.",
                    "Task instructions and the form of the output. What to produce, how much of it, and in what shape.",
                    "Constraints, warnings and verification requirements. What the model must not do, and how it has to prove what it claims.",
                    "Background and context. Everything you know that the model does not. Include as much as you can.",
                    "Optional. The role the model should play while answering.",
                    "Optional. Examples for it to follow.",
                ],
            },
            {
                "heading": "WHAT EACH PART SOUNDS LIKE",
                "body": "The guide walks one worked example through all six parts, a student preparing a talk on AI ethics for other students. The pattern is easy to reuse in any subject.",
                "bullets": [
                    "Goal. I am presenting to a group of college students about ethical issues in artificial intelligence and I need help finding and organising ideas.",
                    "Task and form. Identify the most important issues. Give me eight to ten key points, several bullets under each, cross referenced against classical ethical principles, and suggest visuals.",
                    "Constraints and verification. Use the points in my attached paper. Provide links to every source. Draw only on respected academic publishing.",
                    "Background. I have studied this and written the attached paper. I now need a fifteen minute talk. The audience knows AI only in general terms and most have never studied ethics.",
                    "Role. Answer as the presenter, a student about the same age as the audience.",
                    "Examples. Here is my start on the talk. Critique what I have so far.",
                ],
            },
            {
                "heading": "WHY THE VERIFICATION PART MATTERS MOST",
                "body": "Of the six, the constraints and verification line is the one students skip and the one that does the most work. It is where you tell the model what counts as evidence. Without it you are asking a confident writer for a confident answer, which is exactly what you will get.",
                "bullets": [
                    "Name the kind of source you will accept.",
                    "Ask for a link or a citation for every factual claim.",
                    "Say what the model should do when it is not sure, rather than letting it guess.",
                    "Ask it to flag anything it could not verify.",
                ],
            },
            {
                "heading": "A PROMPT IS A DRAFT TOO",
                "body": "The first prompt is rarely the one that works. Read the answer, find the part of the prompt that let the model wander, and repair that part specifically rather than starting over.",
                "bullets": [
                    "A vague answer usually means a missing goal.",
                    "A wrongly shaped answer means a missing form of output.",
                    "An unsourced answer means a missing verification requirement.",
                    "A generic answer means missing background.",
                ],
            },
        ],
        "so": "You are not writing a question. You are writing a specification, and the six parts are its sections.",
        "exercises": ["prompt_forge", "prompt_rescue"],
    },

    {
        "id": "unit4",
        "number": 4,
        "slug": "read_it_like_an_editor",
        "title": "READ IT LIKE AN EDITOR",
        "blurb": "The output is the beginning of your work, not the end of it.",
        "color": "#5cc4a0", "tint": "#e6f7f0", "dark": "#3d8f72",
        "source": "Paraphrased from pages 9 and 10 of the guide",
        "minutes": 14,
        "cards": [
            {
                "heading": "WHAT GOES WRONG",
                "body": "The guide is direct about the failure modes. Output can sound completely assured while being invented. Models fabricate facts and whole sources, misread what they are given, and draw conclusions their own evidence does not support.",
                "bullets": [
                    "A model does not understand the way you do. It has no lived context, so irony, humour and layered metaphor slip past it.",
                    "Many models know the world only up to a training date and will answer confidently about events after it.",
                    "Bias in the training material comes out in the answer.",
                    "Never stop at the summary. Read the original article and get the detail and the context back.",
                ],
            },
            {
                "heading": "CHECK ONE. ACCURACY AND SOURCES",
                "body": "The first family of checks asks whether the claim is true and whether the thing it rests on exists.",
                "bullets": [
                    "Verify every fact, statistic and data point against several reputable sources rather than one.",
                    "Academic journals, government publications and respected news organisations are what reputable means here.",
                    "If a source is cited, open it and read it yourself.",
                    "If the model cannot produce a source at all, throw the claim away.",
                    "Watch for material that has quietly gone out of date and confirm publication dates.",
                    "Run the same prompt through another model and through an ordinary search engine, then compare.",
                ],
            },
            {
                "heading": "CHECK TWO. BIAS",
                "body": "The second family asks whose view is being presented and whose is missing.",
                "bullets": [
                    "Make sure more than one perspective is represented and none has been quietly dropped.",
                    "Watch for stereotype standing in for evidence.",
                    "Open the original sources and ask whether they lean toward one ideology, group or interest.",
                    "Be alert to material shaped to serve a business, a government, an advocacy campaign or a purchase.",
                ],
            },
            {
                "heading": "CHECK THREE. LOGICAL CONSISTENCY",
                "body": "The third family asks whether the argument actually holds together, independently of whether its facts are real.",
                "bullets": [
                    "Follow the reasoning step by step and confirm each one earns the next.",
                    "Watch for a sweeping generalisation resting on very little evidence.",
                    "Hunt for contradictions and for jumps where a conclusion arrives without support.",
                    "Judge the depth. A tidy but shallow analysis is still a failure.",
                ],
            },
            {
                "heading": "CHECK FOUR. EMOTIONAL AND MANIPULATIVE LANGUAGE",
                "body": "The fourth family asks how the writing is trying to make you feel, and why.",
                "bullets": [
                    "Prefer neutral language built on stated facts.",
                    "Be wary of dramatic or inflammatory phrasing.",
                    "Flag loaded words placed to provoke fear, anger or excitement, or to move you toward an action.",
                ],
            },
            {
                "heading": "CHALLENGE THE ANSWER OUT LOUD",
                "body": "The guide asks you to argue with the model rather than accept it. Require it to justify itself with sources and data, and ask professors and librarians who work with these tools for help when a claim really matters.",
                "bullets": [
                    "Ask it what would have to be true for its answer to be wrong.",
                    "Ask it which part of its own answer it is least sure about.",
                    "Use real time search tools and academic search tools when currency or provenance matters.",
                ],
            },
        ],
        "so": "Four checks, in order. Accuracy, bias, logic, language. Run them every time and the checking becomes fast.",
        "exercises": ["content_audit", "claim_hunt"],
    },

    {
        "id": "unit5",
        "number": 5,
        "slug": "ai_across_your_work",
        "title": "AI ACROSS YOUR WORK",
        "blurb": "Writing, making, counting and studying each have their own safe shape for using a model.",
        "color": "#f0c85e", "tint": "#fffaeb", "dark": "#96793a",
        "source": "Paraphrased from pages 11 through 15 of the guide",
        "minutes": 16,
        "cards": [
            {
                "heading": "WRITING. STAY THE AUTHOR",
                "body": "The rule the guide states first is the one that matters most. Never ask a model to produce a complete first draft that you then hand in as your own. Writing is a form of thinking, and skipping it means skipping the learning.",
                "bullets": [
                    "Use AI at specific stages rather than across the whole task.",
                    "Brainstorming. Explore ideas, test arguments, propose approaches you had not considered.",
                    "Drafting. Ask for several ways your own ideas could be organised for different readers and purposes.",
                    "Revising. Hand over a paragraph you are stuck on, or your finished draft, and ask about tone, clarity and vocabulary.",
                    "Editing. Spelling, punctuation, grammar and citation style.",
                    "Keep a record of how you used it and attribute that use as your assignment requires.",
                    "Work on your own voice. A model will happily flatten it.",
                ],
            },
            {
                "heading": "THE HUMAN AND AI WRITING LOOP",
                "body": "The guide models the whole process as seven turns. You take four of them. The model takes three. Before any of it starts you make sure you understand the assignment and the AI policy that governs it.",
                "bullets": [
                    "One. You gather material, build an outline, and write a detailed prompt asking for three alternative approaches that fit it. Send it to more than one model.",
                    "Two. The model returns three alternatives aligned to your outline.",
                    "Three. You combine what you know with the best of those alternatives and write your own first draft. Then you ask several models to critique it.",
                    "Four. The models critique the draft, name what is missing and correct errors of fact and logic.",
                    "Five. You challenge those suggestions, verify everything, revise, and ask for another pass.",
                    "Six. The models return fixes for spelling, punctuation, grammar and citations.",
                    "Seven. You make sure the paper is in your voice, carries your ideas, meets the assignment, and clearly attributes every way AI was involved.",
                ],
            },
            {
                "heading": "CREATIVE WORK",
                "body": "Generators for image, video, sound and design are catalysts, not collaborators with taste. Use them to break your own thinking open, then make the thing yourself.",
                "bullets": [
                    "Compare output across several systems and blend what you get with your own direction.",
                    "Watch for blandness, stereotype and bias in what comes back.",
                    "Output may lean on copyrighted work, so compare it to what exists and stay away from logos, characters and signature styles.",
                    "Keep a record of the tools, the prompts and the changes you made.",
                    "Disclose AI generated content clearly.",
                    "Never build deepfakes or material meant to harm, mislead or exploit anyone.",
                ],
            },
            {
                "heading": "DATA AND NUMBERS",
                "body": "This is the section students are most surprised by. Current general purpose chat models are poor mathematical instruments. They miscount, fumble word problems and lose their way in many step calculations.",
                "bullets": [
                    "Use purpose built analytical and computational tools for the actual arithmetic.",
                    "Have a model write code only where you can check the result independently.",
                    "Sanity check every number against what you already know about the data. Ask whether the range is even plausible.",
                    "Cross check in a spreadsheet or a statistics package, and confirm the method chosen was the right one.",
                    "Watch for rounding and approximation drift.",
                    "Never hand a model a dataset in a way that breaks somebody else's rights or privacy, and never share data owned by an organisation without permission.",
                ],
            },
            {
                "heading": "STUDY AND LEARNING",
                "body": "This is where a model genuinely shines, as long as it is quizzing you rather than answering for you.",
                "bullets": [
                    "Ask it to test you with questions pitched at what you actually know.",
                    "Ask for diagrams, organised notes, translation, captioning and other access support.",
                    "Prefer tools built to teach rather than to hand over answers.",
                    "Study with people as well. Groups teach you things no model can simulate.",
                    "Always ask everyone present before you record a meeting or a discussion.",
                    "Take your own notes. Processing an idea in your own mind is the point.",
                ],
            },
            {
                "heading": "FOUR STUDY PROMPTS WORTH STEALING",
                "body": "The guide gives four shapes of study prompt. Each one names the material it must work from, which is what keeps the answer anchored.",
                "bullets": [
                    "Summarisation. Summarise the key concepts of a named topic, including these specific definitions, as described in this named chapter.",
                    "Question generation. Generate ten multiple choice questions and five short answer questions on this named topic as explained in this named chapter.",
                    "Elaboration. Elaborate on a named theme in a named work and explain how it develops through the characters, with specific examples from these chapters.",
                    "Practice problems. Generate five problems that require these named rules, and show every step of the solution, referring to this named textbook.",
                ],
            },
        ],
        "so": "Different work, same principle. The model may hold the tools. You hold the pen.",
        "exercises": ["writing_loop"],
    },

    {
        "id": "unit6",
        "number": 6,
        "slug": "integrity_and_attribution",
        "title": "INTEGRITY AND ATTRIBUTION",
        "blurb": "The work you hand in has to be authentically yours, and everyone has to be able to see how it was made.",
        "color": "#c2557f", "tint": "#fdeef4", "dark": "#96637c",
        "source": "Paraphrased from pages 16 and 17 of the guide",
        "minutes": 12,
        "cards": [
            {
                "heading": "THE PRINCIPLE UNDER ALL OF IT",
                "body": "People rationalise. Everybody uses it. It is just another tool. The guide answers both with one line. The work you turn in must be authentically yours. Copying model output word for word and presenting it as your own without attribution is cheating.",
                "bullets": [
                    "Cheating with AI costs you the skill and the confidence you enrolled to build.",
                    "Your development requires you to do the hard part yourself.",
                ],
            },
            {
                "heading": "THE BRIGHT RED LINE",
                "body": "If an instructor says no AI in this course or on this assignment, that is the whole answer. Rules vary between assignments in the same course, and on some assignments you may be required to use AI.",
                "bullets": [
                    "Ask for specific instructions on each assignment rather than assuming last week's rule still holds.",
                    "The safest question is short. What AI use is allowed on this piece of work.",
                ],
            },
            {
                "heading": "WHEN THE LINE IS FUZZY",
                "body": "Plenty of assignments permit AI or require it. The guide gives an order of operations that keeps you the author even then.",
                "bullets": [
                    "Use it first to orient yourself and gather information.",
                    "Then do your own research and produce your own rough draft.",
                    "Only then share that draft and ask what is missing and what could be revised.",
                    "That order leaves you the main author with the model giving feedback.",
                    "Whatever the shape, be honest and transparent about how it contributed.",
                ],
            },
            {
                "heading": "THE FOUR ELEMENTS OF ATTRIBUTION",
                "body": "When you explain how AI was used, the guide asks for four specific things. An attribution missing any of them is incomplete.",
                "bullets": [
                    "Name the specific tools you used.",
                    "State the purpose. Brainstorming, data analysis, image generation, copyediting and so on.",
                    "Assess the extent of the influence as minimal, moderate or extensive.",
                    "Declare the human oversight. Who reviewed and verified the output, and who takes responsibility.",
                ],
            },
            {
                "heading": "FOUR PLACES TO PUT IT",
                "body": "Follow whatever your instructor specifies. Where they leave it open, the guide names four workable homes for an attribution.",
                "bullets": [
                    "In an acknowledgements section, naming the tool, the extent and who takes final responsibility.",
                    "As a cited source in a footnote, an endnote or a bibliography, in the style your course uses.",
                    "In a methodology statement, saying what the AI assisted analysis did and who checked it.",
                    "Inline in the text, at the moment the AI assisted material appears.",
                ],
            },
        ],
        "so": "Attribution is not a confession. It is the ordinary academic habit of showing where anything that is not yours came from.",
        "exercises": ["red_line", "attribution"],
    },

    {
        "id": "unit7",
        "number": 7,
        "slug": "the_ethics_you_inherit",
        "title": "THE ETHICS YOU INHERIT",
        "blurb": "Regulation is behind. That leaves a share of the responsibility sitting with the person typing.",
        "color": "#b9a3e3", "tint": "#f6f1ff", "dark": "#7d6ea8",
        "source": "Paraphrased from page 18 of the guide",
        "minutes": 12,
        "cards": [
            {
                "heading": "PRIVACY AND SAFETY",
                "body": "Anything you type into a model may be reachable in ways you cannot control, by companies and by governments. The guide notes that this matters most sharply in authoritarian states where surveillance is routine.",
                "bullets": [
                    "Go into the settings and turn off training on your data.",
                    "Never share information about another person without their permission.",
                    "Assume a prompt is not private until you have checked that it is.",
                ],
            },
            {
                "heading": "BIAS AND FAIRNESS",
                "body": "Models are built from enormous amounts of material, much of it written in English. Prejudice and error in that material comes through into the output, and so can state propaganda, censorship and corporate restriction.",
                "bullets": [
                    "Recognising the bias is the user's job, because nothing in the interface will do it for you.",
                    "Do not pass on a false or stereotyped narrative just because a model produced it fluently.",
                ],
            },
            {
                "heading": "MISUSE",
                "body": "These systems can fabricate photographs, video and audio, and can be pushed toward instructions for disinformation, cyberattack and violence. Even a small careless use, like an AI written social post, can travel further than you intended.",
                "bullets": [
                    "Handle powerful tools with matching care.",
                    "Ask who could be harmed if what you are about to make escaped your control.",
                ],
            },
            {
                "heading": "INTELLECTUAL PROPERTY",
                "body": "Models are often trained on copyrighted work without the creator's permission, which leaves ownership genuinely unsettled. Treat output like any other information you did not write.",
                "bullets": [
                    "Do not assume output is free to reuse. Check the rights on the underlying work.",
                    "If you use it, change it substantially and add real value of your own.",
                    "Prefer tools that are open about their training data and their licensing.",
                ],
            },
            {
                "heading": "ENVIRONMENTAL COST",
                "body": "Building and running these systems pushes energy demand up, alongside streaming, cryptocurrency and the rest of the digital economy. The guide asks you not to treat the resource as limitless.",
                "bullets": [
                    "Do not burn a large model on something trivial that a smaller tool or your own head would settle.",
                ],
            },
            {
                "heading": "THE BIGGER PICTURE",
                "body": "The guide names the societal issues students will live inside for the whole of their careers.",
                "bullets": [
                    "Job loss, economic upheaval and widening income inequality.",
                    "Overreliance, and the human capability that quietly wastes away with it.",
                    "A digital divide between those with AI access and knowledge and those without.",
                    "New pressure on civil and political rights as data collection and surveillance get cheaper.",
                    "Power imbalance between nations that hold advanced AI and nations that do not.",
                    "Loss of human control over the systems themselves.",
                ],
            },
        ],
        "so": "Governments and companies have a great deal of work left to do. Until they finish it, part of the burden is personal.",
        "exercises": ["ethics_triage"],
    },

    {
        "id": "unit8",
        "number": 8,
        "slug": "a_two_part_career_plan",
        "title": "A TWO PART CAREER PLAN",
        "blurb": "Become fluent with the machine and unmistakably good at what it cannot do. Both halves, at the same time.",
        "color": "#5cc4a0", "tint": "#e6f7f0", "dark": "#3d8f72",
        "source": "Paraphrased from pages 19 through 23 of the guide",
        "minutes": 14,
        "cards": [
            {
                "heading": "PART ONE. STRENGTHEN WHAT IS HUMAN",
                "body": "As the tools get stronger the distinctly human capabilities get more valuable, not less. Employers surveyed for the World Economic Forum report named analytical thinking, resilience and flexibility, leadership and social influence, creative thinking, motivation and self awareness, and technological literacy as the skills they look for.",
                "bullets": [
                    "Critical thinking. Reading a complicated situation, spotting a bad assumption, a broken argument and an unreliable source.",
                    "Creativity and innovation. New ideas, unfamiliar solutions, comfort with ambiguity, a willingness to push back on received wisdom.",
                    "Emotional intelligence. Empathy, real listening, conflict resolution and negotiation, reading a room, working across cultures, self regulation.",
                    "Ethical judgement. Recognising moral complexity, arguing for it, and setting your own boundaries.",
                    "Strategic thinking. Seeing past the immediate problem to what it implies, and planning for risk.",
                    "Leadership and collaboration. Motivating people, delegating, giving and taking feedback, building agreement.",
                ],
            },
            {
                "heading": "HOW THOSE SKILLS ACTUALLY GET BUILT",
                "body": "None of them are built by reading about them. The guide points at the ordinary structures of university life.",
                "bullets": [
                    "Find mentors who will tell you the truth about your work.",
                    "Take classes and seminars aimed at your own growth rather than only at credits.",
                    "Take a leadership role in a student or professional organisation.",
                    "Join group projects, research and community work.",
                    "Make an internship a priority rather than an afterthought.",
                ],
            },
            {
                "heading": "PART TWO. BECOME AI LITERATE",
                "body": "The same employer survey found that the overwhelming majority expect AI to drive business transformation and say AI skills are becoming more important, with most planning to hire for exactly that.",
                "bullets": [
                    "Fundamentals. Writing effective prompts, fact checking output, combining several tools, writing and editing with AI, working ethically.",
                    "Technical understanding. How the different kinds of system work, and where their limits and biases sit.",
                    "Professional application. The tools specific to your field, plus research, analysis and visualisation.",
                    "Integration. Workflows and documentation that combine machine and human input, quality control on output, and keeping data secure and private.",
                ],
            },
            {
                "heading": "BUILD A PORTFOLIO",
                "body": "The guide's closing advice is to show rather than claim. A portfolio of hands on projects makes your ability legible to somebody who has never met you.",
                "bullets": [
                    "Take courses and certifications, and get to know the professors who work with these tools.",
                    "Share the work at research fairs, on professional networks and on your own site.",
                    "In science and engineering, analyse a real dataset, work with prediction, or build something that detects an anomaly.",
                    "In business, run market research, segmentation or logistics through AI assisted analysis and defend the result.",
                    "In arts and humanities, compare human and machine translation for nuance, or analyse a large historical dataset.",
                    "In social and health sciences, look for pattern in real data and be careful about what the pattern does and does not prove.",
                ],
            },
            {
                "heading": "THE CRYSTAL BALL",
                "body": "The guide closes with experts imagining the next decade. Their questions are worth carrying with you.",
                "bullets": [
                    "Will these tools feed human curiosity or become crutches we cannot put down.",
                    "One expert names the risk of cognitive abilities wasting away through overreliance.",
                    "Another expects proof of humanity to become something we routinely have to establish.",
                    "Another imagines agents taking hours of digital chores a day and freeing people for what only people do.",
                    "Another sees a choice opening between remaining a classic human and accepting technological augmentation.",
                ],
            },
        ],
        "so": "Two superpowers, learned together, in the same four years. That is the whole assignment.",
        "exercises": ["career_plan"],
    },
]

UNIT_BY_ID = {u["id"]: u for u in UNITS}


# ─────────────────────────────────────────────────────────────────────────────
# EXERCISES
#
# Seven interaction kinds, so the course never feels like one form repeated.
#
#   fields  N labelled boxes. Claude returns a verdict per box.
#   single  one box. Claude returns a verdict per component it finds inside it.
#   checks  a checklist over a sample, plus a short written finding.
#   match   pair each item with one option. Marked here, with no model involved.
#   sorter  drop each item into one of several buckets. Claude marks each drop.
#   hunt    click the sentences in a passage that need verifying. Claude marks each.
#   order   put the steps of a process back in sequence. Marked here.
# ─────────────────────────────────────────────────────────────────────────────

EXERCISES = {

    # ── UNIT 1 ───────────────────────────────────────────────────────────────
    "tool_match": {
        "id": "tool_match",
        "unit": "unit1",
        "kind": "match",
        "title": "PICK THE RIGHT FAMILY",
        "tagline": "Six jobs. Six families of tool. Marked instantly, right here, with no model involved.",
        "intro": "Not every task wants a chat window. Read each job and choose the family of tool the guide would point you at.",
        "options": [
            "A general chat assistant",
            "A specialist research or coding tool",
            "A creative generator for image, video or sound",
            "An analytical or computational tool",
            "An assistant embedded in software you already use",
            "An open or customisable model from a community hub",
        ],
        "items": [
            {"key": "m1", "text": "You need the standard deviation of a column of four thousand readings, and you need it to be right.", "answer": 3},
            {"key": "m2", "text": "You want three different ways of framing an argument you are stuck on.", "answer": 0},
            {"key": "m3", "text": "You want peer reviewed papers on one narrow question, with the papers themselves.", "answer": 1},
            {"key": "m4", "text": "You want background music for a short film you are cutting tonight.", "answer": 2},
            {"key": "m5", "text": "You want your slide deck tidied up without leaving the slide software.", "answer": 4},
            {"key": "m6", "text": "You want to run a model you can inspect and adapt, on your own terms.", "answer": 5},
        ],
        "pass_mark": 5,
        "reward": "One correct family beats one clever prompt aimed at the wrong tool.",
    },

    # ── UNIT 2 ───────────────────────────────────────────────────────────────
    "lean_check": {
        "id": "lean_check",
        "unit": "unit2",
        "kind": "sorter",
        "title": "AUGMENT OR REPLACE",
        "tagline": "Eight real uses. Claude judges every call you make and says why.",
        "intro": "The whole guide turns on one distinction. Put each use where you think it belongs, then press execute and defend your instincts against a second opinion.",
        "buckets": [
            {"key": "augment", "label": "AUGMENTS ME", "color": "#5cc4a0", "tint": "#e6f7f0"},
            {"key": "replace", "label": "REPLACES ME", "color": "#e79ec0", "tint": "#fdeef4"},
        ],
        "items": [
            {"key": "a1", "text": "Asking for ten practice problems on the rule you keep getting wrong, with worked solutions to check yourself against afterwards."},
            {"key": "a2", "text": "Asking for the finished essay because it is due at midnight."},
            {"key": "a3", "text": "Asking for the three strongest arguments against your thesis so you can answer them."},
            {"key": "a4", "text": "Pasting the reading and using the summary instead of the reading."},
            {"key": "a5", "text": "Asking a model to quiz you on a chapter and refusing to see the answers until you have committed to yours."},
            {"key": "a6", "text": "Asking it to explain a proof step you cannot follow, in three different ways, until one lands."},
            {"key": "a7", "text": "Handing over your lab data and reporting the numbers it returns without checking any of them."},
            {"key": "a8", "text": "Asking it to critique a draft you wrote yourself and tell you what a reader would not follow."},
        ],
        "reward": "The same tool sits on both sides of that line. Only your next move decides which.",
    },

    # ── UNIT 3 ───────────────────────────────────────────────────────────────
    "prompt_forge": {
        "id": "prompt_forge",
        "unit": "unit3",
        "kind": "fields",
        "title": "THE PROMPT FORGE",
        "tagline": "Build all six parts. Press execute. Claude marks each part green or red on its own.",
        "intro": "Here is your assignment. You have to write a three page briefing for a first year seminar on why misinformation spreads faster than corrections. Build the prompt you would send, one part at a time. Each box is graded by itself, so a strong goal will pass even if your constraints need work.",
        "scenario": "A three page briefing for a first year seminar on why misinformation spreads faster than corrections.",
        "fields": [
            {"key": "goal", "label": "YOUR GOAL", "color": "#7fc4e8",
             "hint": "The outcome you are actually after, not the request. Who is it for and what has to be true when you are done.",
             "placeholder": "I am writing a three page briefing for..."},
            {"key": "task", "label": "TASK INSTRUCTIONS AND FORM OF OUTPUT", "color": "#a98fd4",
             "hint": "What to produce, how much of it, and in what shape. Counts, sections, ordering.",
             "placeholder": "Give me an outline with five sections, each with..."},
            {"key": "constraints", "label": "CONSTRAINTS, WARNINGS AND VERIFICATION", "color": "#e79ec0",
             "hint": "What it must not do, what counts as an acceptable source, and how it has to prove each claim.",
             "placeholder": "Use only peer reviewed work. Give a link for every claim. Flag anything you cannot..."},
            {"key": "context", "label": "BACKGROUND AND CONTEXT", "color": "#5cc4a0",
             "hint": "Everything you know that the model does not. The guide says to include as much as you can.",
             "placeholder": "The seminar has already read... My own view is... The audience knows..."},
            {"key": "role", "label": "THE ROLE IT SHOULD PLAY", "color": "#f0c85e", "optional": True,
             "hint": "Optional. Who is speaking, and to whom.",
             "placeholder": "Answer as a research librarian briefing first year students..."},
            {"key": "examples", "label": "EXAMPLES TO FOLLOW", "color": "#b9a3e3", "optional": True,
             "hint": "Optional. A sample of the shape or voice you want, or your own draft for critique.",
             "placeholder": "Here is a paragraph in the register I want..."},
        ],
        "pass_mark": 4,
        "reward": "Six parts, six separate judgements. That is how a prompt gets repaired instead of rewritten.",
    },

    "prompt_rescue": {
        "id": "prompt_rescue",
        "unit": "unit3",
        "kind": "single",
        "title": "PROMPT RESCUE",
        "tagline": "One weak prompt. Rewrite it in one box. Claude reports which of the six parts you managed to smuggle in.",
        "intro": "Below is a prompt a student actually sent. Rewrite it as one paragraph so that as many of the six parts as possible are genuinely present. You are not being marked on length. You are being marked on whether each part is really there and really specific.",
        "sample": "write me something about climate change for my class",
        "sample_label": "THE PROMPT AS SENT",
        "field": {
            "key": "prompt", "label": "YOUR REWRITE", "rows": 8,
            "placeholder": "Write the whole thing here as one paragraph...",
        },
        "components": [
            {"key": "goal", "label": "GOAL", "color": "#7fc4e8"},
            {"key": "task", "label": "TASK AND FORM", "color": "#a98fd4"},
            {"key": "constraints", "label": "CONSTRAINTS AND VERIFICATION", "color": "#e79ec0"},
            {"key": "context", "label": "BACKGROUND", "color": "#5cc4a0"},
            {"key": "role", "label": "ROLE", "color": "#f0c85e", "optional": True},
            {"key": "examples", "label": "EXAMPLES", "color": "#b9a3e3", "optional": True},
        ],
        "pass_mark": 4,
        "reward": "Same six parts, one paragraph. This is the version you will actually type at midnight.",
    },

    # ── UNIT 4 ───────────────────────────────────────────────────────────────
    "content_audit": {
        "id": "content_audit",
        "unit": "unit4",
        "kind": "checks",
        "title": "THE FOUR CHECKS",
        "tagline": "A real looking AI answer. Tick every check it fails. Claude marks each tick green or red.",
        "intro": "Here is a passage a model produced. Run the guide's four families of check over it and tick every statement that is genuinely true of this passage. Ticking everything is not a strategy. A tick that does not hold up will come back red.",
        "sample_label": "THE AI GENERATED PASSAGE",
        "sample": (
            "Recent work has settled the question decisively. A 2024 Stanford study found that "
            "students who used AI tutors scored 47 percent higher on final examinations than students "
            "who did not, which proves that AI tutoring is superior to classroom teaching in every "
            "subject. Critics of educational technology have never produced comparable evidence, and "
            "their objections are largely driven by a fear of change. Every serious researcher now "
            "accepts that traditional lecturing is obsolete, and institutions that refuse to adapt are "
            "failing their students. The finding held across all demographics, so no further study is "
            "required before schools act on it."
        ),
        "groups": [
            {"label": "ACCURACY AND SOURCE CHECK", "color": "#7fc4e8"},
            {"label": "BIAS CHECK", "color": "#a98fd4"},
            {"label": "LOGICAL CONSISTENCY CHECK", "color": "#5cc4a0"},
            {"label": "EMOTIONAL AND MANIPULATIVE LANGUAGE CHECK", "color": "#e79ec0"},
        ],
        "items": [
            {"key": "c1", "group": 0, "text": "A specific statistic is given with no traceable citation behind it."},
            {"key": "c2", "group": 0, "text": "The study is named vaguely enough that it cannot be located and read."},
            {"key": "c3", "group": 0, "text": "Every number in the passage is supported by a source I could open."},
            {"key": "c4", "group": 1, "text": "Opposing views are dismissed by motive rather than answered on evidence."},
            {"key": "c5", "group": 1, "text": "Only one perspective on the question is represented at all."},
            {"key": "c6", "group": 1, "text": "The passage carefully presents more than one side of the argument."},
            {"key": "c7", "group": 2, "text": "A single result is treated as proof of a sweeping general claim."},
            {"key": "c8", "group": 2, "text": "The conclusion that no further study is needed does not follow from what came before."},
            {"key": "c9", "group": 2, "text": "One subject area is generalised to every subject without warrant."},
            {"key": "c10", "group": 3, "text": "Words like decisively and obsolete are doing work that evidence should be doing."},
            {"key": "c11", "group": 3, "text": "The passage frames disagreement as failure, which pressures the reader rather than informing them."},
            {"key": "c12", "group": 3, "text": "The tone is neutral and measured throughout."},
        ],
        "note_label": "WRITE THE ONE SENTENCE YOU WOULD SEND BACK TO THE MODEL",
        "note_placeholder": "Ask it for the one thing that would settle the biggest problem here...",
        "pass_mark": 7,
        "reward": "Four families of check, run in order, take about ninety seconds once you have done it twice.",
    },

    "claim_hunt": {
        "id": "claim_hunt",
        "unit": "unit4",
        "kind": "hunt",
        "title": "CLAIM HUNT",
        "tagline": "Click every sentence you would refuse to use before verifying it. Claude marks each click.",
        "intro": "A model wrote the following for a history assignment. Click the sentences that carry a checkable factual claim you would have to verify before putting your name on them. Leave the rest alone.",
        "sample_label": "THE DRAFT PARAGRAPH",
        "sentences": [
            {"key": "s1", "text": "The printing press changed how quickly ideas could travel across Europe."},
            {"key": "s2", "text": "Gutenberg completed his first press in Mainz in exactly 1439."},
            {"key": "s3", "text": "Within forty years there were more than one thousand print shops operating in over two hundred European cities."},
            {"key": "s4", "text": "This is often described as a communications revolution."},
            {"key": "s5", "text": "A 2019 paper in the Journal of Early Modern Communication put the literacy increase at 31 percent in the affected regions."},
            {"key": "s6", "text": "Historians continue to disagree about how much of that change the press itself caused."},
            {"key": "s7", "text": "The Catholic Church banned all printing outright in 1487."},
        ],
        "note_label": "NAME THE ONE SENTENCE YOU WOULD CHECK FIRST AND SAY WHY",
        "note_placeholder": "I would start with... because...",
        "pass_mark": 5,
        "reward": "A named study, a precise date and a precise percentage are exactly where fabrication likes to hide.",
    },

    # ── UNIT 5 ───────────────────────────────────────────────────────────────
    "writing_loop": {
        "id": "writing_loop",
        "unit": "unit5",
        "kind": "order",
        "title": "REBUILD THE LOOP",
        "tagline": "Seven turns, shuffled. Put them back in order. Marked right here.",
        "intro": "The guide models writing with AI as seven turns. Four are yours and three are the model's. Click them into the right order. Getting this sequence wrong is how students end up with a machine written paper they cannot defend.",
        "steps": [
            {"key": "w1", "who": "YOU", "text": "Gather material, build your outline, and write a detailed prompt asking several models for three alternative approaches that fit it."},
            {"key": "w2", "who": "THE MODEL", "text": "Returns three alternative approaches aligned to your outline."},
            {"key": "w3", "who": "YOU", "text": "Combine what you know with the best of those approaches and write your own first draft, then ask several models to critique it."},
            {"key": "w4", "who": "THE MODEL", "text": "Returns a detailed critique, names what is missing and corrects errors of fact and logic."},
            {"key": "w5", "who": "YOU", "text": "Challenge those suggestions, verify everything, revise, and ask for another pass."},
            {"key": "w6", "who": "THE MODEL", "text": "Returns fixes for spelling, punctuation, grammar and citation."},
            {"key": "w7", "who": "YOU", "text": "Make sure the paper is in your voice, carries your ideas, meets the assignment, and attributes every way AI was involved."},
        ],
        "reward": "Notice where your first draft sits. Turn three, not turn one. That single fact is most of academic integrity.",
    },

    # ── UNIT 6 ───────────────────────────────────────────────────────────────
    "red_line": {
        "id": "red_line",
        "unit": "unit6",
        "kind": "sorter",
        "title": "WHERE IS THE RED LINE",
        "tagline": "Seven situations, three verdicts. Claude marks every call and explains the ones you miss.",
        "intro": "Sort each situation. The middle bucket is not a hiding place. It is for cases where the honest answer really is that you cannot know without asking, and asking is the whole move.",
        "buckets": [
            {"key": "fine", "label": "CLEARLY FINE", "color": "#5cc4a0", "tint": "#e6f7f0"},
            {"key": "ask", "label": "ASK FIRST", "color": "#f0c85e", "tint": "#fffaeb"},
            {"key": "over", "label": "OVER THE LINE", "color": "#e79ec0", "tint": "#fdeef4"},
        ],
        "items": [
            {"key": "r1", "text": "Your instructor said no AI on this essay. You used a model to check your grammar at the end."},
            {"key": "r2", "text": "You asked a model to explain a concept from the reading before you started writing anything, on an assignment with no stated policy."},
            {"key": "r3", "text": "You generated the full draft, changed some wording, and submitted it with no attribution."},
            {"key": "r4", "text": "You wrote your own draft, then asked three models what a reader would find unclear, and revised it yourself."},
            {"key": "r5", "text": "The syllabus permits AI for brainstorming. You want to use it to generate your data analysis code as well."},
            {"key": "r6", "text": "You used a model to translate a source written in a language you do not read, and said so in your notes."},
            {"key": "r7", "text": "A group member fed the whole team's unpublished project into a public model to get feedback, without telling anyone."},
        ],
        "reward": "Almost every fuzzy case collapses the moment you send one short message to your instructor.",
    },

    "attribution": {
        "id": "attribution",
        "unit": "unit6",
        "kind": "single",
        "title": "WRITE THE ATTRIBUTION",
        "tagline": "Four required elements. Claude tells you which ones are actually in your sentence.",
        "intro": "You used a model to brainstorm angles for a paper and to tidy the grammar of your final draft. You wrote every argument yourself and checked every claim. Write the attribution statement you would put in your acknowledgements. All four elements have to be genuinely present.",
        "sample_label": "WHAT ACTUALLY HAPPENED",
        "sample": (
            "You asked two different assistants for possible angles before you began. You discarded most of "
            "them and kept one. You wrote the whole draft yourself. At the end you asked one assistant to "
            "check grammar and citation formatting. You verified every factual claim against the original "
            "sources yourself and you take responsibility for the finished paper."
        ),
        "field": {
            "key": "statement", "label": "YOUR ATTRIBUTION STATEMENT", "rows": 6,
            "placeholder": "The author acknowledges...",
        },
        "components": [
            {"key": "tools", "label": "THE SPECIFIC TOOLS NAMED", "color": "#7fc4e8"},
            {"key": "purpose", "label": "THE PURPOSE OF THE USE", "color": "#a98fd4"},
            {"key": "extent", "label": "THE EXTENT OF THE INFLUENCE", "color": "#e79ec0"},
            {"key": "oversight", "label": "THE HUMAN OVERSIGHT AND RESPONSIBILITY", "color": "#5cc4a0"},
        ],
        "pass_mark": 4,
        "reward": "Tool, purpose, extent, oversight. Four clauses, and the whole question of honesty is settled.",
    },

    # ── UNIT 7 ───────────────────────────────────────────────────────────────
    "ethics_triage": {
        "id": "ethics_triage",
        "unit": "unit7",
        "kind": "checks",
        "title": "ETHICS TRIAGE",
        "tagline": "One ordinary decision. Tick every issue genuinely in play, then write the fix. Claude marks both.",
        "intro": "This is not a dramatic case. It is a Tuesday. Tick every ethical issue that is actually live here, then write what you would do differently. Ticking all of them is not the answer.",
        "sample_label": "THE SITUATION",
        "sample": (
            "You are running a group project on student mental health. To save time you paste the whole "
            "survey spreadsheet, which still has respondent names and their free text answers in it, into a "
            "free chat assistant and ask it to find themes and generate a chart. You copy the themes and an "
            "AI generated stock illustration of a student into the slides. Nobody outside the group is told "
            "any of this happened. The assistant is on its default settings."
        ),
        "groups": [
            {"label": "TICK EVERY ISSUE THAT IS ACTUALLY IN PLAY", "color": "#b9a3e3"},
        ],
        "items": [
            {"key": "e1", "group": 0, "text": "Personal information about other people was shared without their permission."},
            {"key": "e2", "group": 0, "text": "The default settings probably allow this data to be used for training."},
            {"key": "e3", "group": 0, "text": "A general chat model is a poor instrument for the numerical part of this work."},
            {"key": "e4", "group": 0, "text": "The use of AI was never disclosed to anyone who reads the slides."},
            {"key": "e5", "group": 0, "text": "The generated illustration may carry stereotype into the presentation."},
            {"key": "e6", "group": 0, "text": "The rights position of the generated image was never checked."},
            {"key": "e7", "group": 0, "text": "Using AI for a group project is itself a breach of academic integrity."},
            {"key": "e8", "group": 0, "text": "Nobody verified the themes against the original responses."},
        ],
        "note_label": "WRITE WHAT YOU WOULD DO INSTEAD",
        "note_placeholder": "Before pasting anything I would...",
        "pass_mark": 6,
        "reward": "The ethics of this are not exotic. They are consent, settings, competence, disclosure and verification.",
    },

    # ── UNIT 8 ───────────────────────────────────────────────────────────────
    "career_plan": {
        "id": "career_plan",
        "unit": "unit8",
        "kind": "fields",
        "title": "YOUR TWO PART PLAN",
        "tagline": "Both halves, written for your actual life. Claude marks each half on whether it is specific enough to act on.",
        "intro": "The guide asks for a plan with two halves held at once. Write yours. Vague answers come back red, because a plan you cannot start this month is not a plan.",
        "fields": [
            {"key": "human", "label": "HOW YOU WILL STRENGTHEN WHAT IS HUMAN", "color": "#5cc4a0",
             "hint": "Name the capability, and name the concrete thing you will join, take or lead this year to build it.",
             "placeholder": "The capability I most need is... I will build it by..."},
            {"key": "literacy", "label": "HOW YOU WILL BECOME AI LITERATE", "color": "#7fc4e8",
             "hint": "Fundamentals, technical understanding, the tools of your field, or integration. Pick and be specific.",
             "placeholder": "In my field the tools that matter are... I will learn them by..."},
            {"key": "portfolio", "label": "THE FIRST PROJECT FOR YOUR PORTFOLIO", "color": "#f0c85e",
             "hint": "One project, in your discipline, that somebody could open and understand without meeting you.",
             "placeholder": "I will build... using... and I will show it by..."},
        ],
        "pass_mark": 3,
        "reward": "Two superpowers, learned in the same four years. You have just written the first month of it.",
    },
}

EXERCISE_ORDER = [e for u in UNITS for e in u["exercises"]]
for _u in UNITS:
    _u["exercise_specs"] = [EXERCISES[e] for e in _u["exercises"]]


# ─────────────────────────────────────────────────────────────────────────────
# ACHIEVEMENTS
#
# A rule is a small dict the evaluator below understands. Nothing here touches
# the database. app.py hands us a learner's finished items and we hand back the
# codes they have now earned.
# ─────────────────────────────────────────────────────────────────────────────

ACHIEVEMENTS = [
    {"code": "first_light", "title": "FIRST LIGHT", "mark": "✦", "color": "#f0c85e", "tint": "#fffaeb",
     "note": "You made an account and opened the curriculum.",
     "rule": {"type": "account"}},

    {"code": "unit1", "title": "TOOL SENSE", "mark": "1", "color": "#7fc4e8", "tint": "#f2fafe",
     "note": "You finished the unit on where AI already lives.",
     "rule": {"type": "item", "key": "unit1"}},

    {"code": "unit2", "title": "AUGMENT NOT REPLACE", "mark": "2", "color": "#a98fd4", "tint": "#f6f1ff",
     "note": "You finished the unit on what AI means for your education.",
     "rule": {"type": "item", "key": "unit2"}},

    {"code": "unit3", "title": "SIX PARTS", "mark": "3", "color": "#e79ec0", "tint": "#fdeef4",
     "note": "You finished the unit on the anatomy of a prompt.",
     "rule": {"type": "item", "key": "unit3"}},

    {"code": "unit4", "title": "EDITOR EYES", "mark": "4", "color": "#5cc4a0", "tint": "#e6f7f0",
     "note": "You finished the unit on reading AI output like an editor.",
     "rule": {"type": "item", "key": "unit4"}},

    {"code": "unit5", "title": "STILL THE AUTHOR", "mark": "5", "color": "#f0c85e", "tint": "#fffaeb",
     "note": "You finished the unit on AI across writing, making, counting and studying.",
     "rule": {"type": "item", "key": "unit5"}},

    {"code": "unit6", "title": "HONEST WORK", "mark": "6", "color": "#c2557f", "tint": "#fdeef4",
     "note": "You finished the unit on integrity and attribution.",
     "rule": {"type": "item", "key": "unit6"}},

    {"code": "unit7", "title": "EYES OPEN", "mark": "7", "color": "#b9a3e3", "tint": "#f6f1ff",
     "note": "You finished the unit on the ethics you inherit.",
     "rule": {"type": "item", "key": "unit7"}},

    {"code": "unit8", "title": "TWO SUPERPOWERS", "mark": "8", "color": "#5cc4a0", "tint": "#e6f7f0",
     "note": "You finished the unit on building a two part career plan.",
     "rule": {"type": "item", "key": "unit8"}},

    {"code": "forged", "title": "THE FORGE", "mark": "✎", "color": "#e79ec0", "tint": "#fdeef4",
     "note": "You built a prompt whose parts stood up to inspection one at a time.",
     "rule": {"type": "item", "key": "ex.prompt_forge"}},

    {"code": "rescuer", "title": "RESCUER", "mark": "↻", "color": "#a98fd4", "tint": "#f6f1ff",
     "note": "You rebuilt a weak prompt into one that carries its own parts.",
     "rule": {"type": "item", "key": "ex.prompt_rescue"}},

    {"code": "auditor", "title": "THE AUDITOR", "mark": "✓", "color": "#5cc4a0", "tint": "#e6f7f0",
     "note": "You ran all four checks over a passage and made them stick.",
     "rule": {"type": "item", "key": "ex.content_audit"}},

    {"code": "hunter", "title": "CLAIM HUNTER", "mark": "◎", "color": "#7fc4e8", "tint": "#f2fafe",
     "note": "You picked out the sentences that had to be verified before use.",
     "rule": {"type": "item", "key": "ex.claim_hunt"}},

    {"code": "attributor", "title": "ON THE RECORD", "mark": "§", "color": "#c2557f", "tint": "#fdeef4",
     "note": "You wrote an attribution carrying all four required elements.",
     "rule": {"type": "item", "key": "ex.attribution"}},

    {"code": "planner", "title": "THE PLAN", "mark": "★", "color": "#f0c85e", "tint": "#fffaeb",
     "note": "You wrote a two part career plan specific enough to start this month.",
     "rule": {"type": "item", "key": "ex.career_plan"}},

    {"code": "halfway", "title": "HALFWAY UP", "mark": "▲", "color": "#7fc4e8", "tint": "#f2fafe",
     "note": "You finished four of the eight units.",
     "rule": {"type": "units", "count": 4}},

    {"code": "workshop", "title": "THE WHOLE WORKSHOP", "mark": "✺", "color": "#a98fd4", "tint": "#f6f1ff",
     "note": "You cleared every interactive exercise in the course.",
     "rule": {"type": "all_exercises"}},

    {"code": "graduate", "title": "FULL CIRCLE", "mark": "✿", "color": "#5cc4a0", "tint": "#e6f7f0",
     "note": "Eight units and every exercise. You can now argue with a model and win.",
     "rule": {"type": "everything"}},
]

ACHIEVEMENT_BY_CODE = {a["code"]: a for a in ACHIEVEMENTS}

UNIT_KEYS = [u["id"] for u in UNITS]
EXERCISE_KEYS = ["ex." + e for e in EXERCISE_ORDER]
ALL_KEYS = UNIT_KEYS + EXERCISE_KEYS


def earned_codes(finished: set[str]) -> list[str]:
    """Which achievement codes a learner with these finished items now holds."""
    units_done = sum(1 for k in UNIT_KEYS if k in finished)
    exercises_done = sum(1 for k in EXERCISE_KEYS if k in finished)
    out = []
    for badge in ACHIEVEMENTS:
        rule = badge["rule"]
        kind = rule["type"]
        if kind == "account":
            ok = True
        elif kind == "item":
            ok = rule["key"] in finished
        elif kind == "units":
            ok = units_done >= rule["count"]
        elif kind == "all_exercises":
            ok = exercises_done >= len(EXERCISE_KEYS)
        elif kind == "everything":
            ok = units_done >= len(UNIT_KEYS) and exercises_done >= len(EXERCISE_KEYS)
        else:
            ok = False
        if ok:
            out.append(badge["code"])
    return out


def public_units() -> list[dict]:
    """The whole course, shaped for the page that renders it."""
    return [
        {
            "id": u["id"], "number": u["number"], "title": u["title"], "blurb": u["blurb"],
            "color": u["color"], "tint": u["tint"], "dark": u["dark"],
            "source": u["source"], "minutes": u["minutes"], "cards": u["cards"], "so": u["so"],
            "exercises": [public_exercise(e) for e in u["exercises"]],
        }
        for u in UNITS
    ]


_ANSWER_KEYS = ("answer", "answers", "correct", "order")


def public_exercise(exercise_id: str) -> dict:
    """One exercise with every answer key stripped out before it reaches a browser."""
    spec = EXERCISES[exercise_id]
    out = {}
    for key, value in spec.items():
        if key in _ANSWER_KEYS:
            continue
        if key in ("items", "sentences"):
            out[key] = [{k: v for k, v in item.items() if k not in _ANSWER_KEYS}
                        for item in value]
        elif key == "steps":
            out[key] = [dict(step) for step in value]
        else:
            out[key] = value
    return out


# ─────────────────────────────────────────────────────────────────────────────
# ANSWER KEYS
#
# Claude does the marking in the browser, because being argued with by a model
# is the point of the exercise. These keys are the fallback used when no API key
# is configured or a call fails, and they are stripped out of everything sent to
# a browser by public_exercise above.
# ─────────────────────────────────────────────────────────────────────────────

_ANSWERS = {
    "lean_check": {
        "a1": "augment", "a2": "replace", "a3": "augment", "a4": "replace",
        "a5": "augment", "a6": "augment", "a7": "replace", "a8": "augment",
    },
    "red_line": {
        "r1": "over", "r2": "fine", "r3": "over", "r4": "fine",
        "r5": "ask", "r6": "ask", "r7": "over",
    },
    "content_audit": {
        "c1": True, "c2": True, "c3": False, "c4": True, "c5": True, "c6": False,
        "c7": True, "c8": True, "c9": True, "c10": True, "c11": True, "c12": False,
    },
    "claim_hunt": {
        "s1": False, "s2": True, "s3": True, "s4": False,
        "s5": True, "s6": False, "s7": True,
    },
    "ethics_triage": {
        "e1": True, "e2": True, "e3": True, "e4": True,
        "e5": True, "e6": True, "e7": False, "e8": True,
    },
}

for _eid, _mapping in _ANSWERS.items():
    _spec = EXERCISES[_eid]
    for _list_key in ("items", "sentences"):
        for _item in _spec.get(_list_key, []):
            if _item["key"] in _mapping:
                _item["answer"] = _mapping[_item["key"]]

# The writing loop is correct in the order it is written above.
EXERCISES["writing_loop"]["order"] = [s["key"] for s in EXERCISES["writing_loop"]["steps"]]
